server:
  log_level: warn

metrics:
  global:
    scrape_interval: 5s
  configs:
    - name: paystream
      scrape_configs:
        - job_name: paystream_backend
          static_configs:
            - targets: ['localhost:8000']
      remote_write:
        - url: ${GRAFANA_REMOTE_WRITE_URL}
          basic_auth:
            username: ${GRAFANA_USERNAME}
            password: ${GRAFANA_API_KEY}
